name: Main Stroyka bot workflow

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Yandex Container Registry
      uses: docker/login-action@v2
      with:
        registry: cr.yandex
        username: ${{ secrets.YC_ACCESS_KEY_ID }}
        password: ${{ secrets.YC_SECRET_ACCESS_KEY }}

    - name: Build and Push image to YCR
      run: |
        docker build -t cr.yandex/${{ secrets.YC_REGISTRY_ID }}/stroyka-bot:latest -f bot/Dockerfile .
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/stroyka-bot:latest

    - name: Copy docker-compose to VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        source: docker-compose.yml
        target: /home/${{ secrets.VM_USER }}/

    - name: Deploy to VM
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          docker pull cr.yandex/${{ secrets.YC_REGISTRY_ID }}/stroyka-bot:latest
          docker-compose -f /home/${{ secrets.VM_USER }}/docker-compose.yml up -d --remove-orphans

  send_message:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            В ${{ github.repository }}
            ${{ github.actor }} запушил с коммитом
            "${{ github.event.commits[0].message }}"
            Деплой foodgram успешно выполнен!

