name: Deploy to Yandex Cloud VM

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/stroyka-bot:latest

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Yandex Cloud CLI
        uses: yandex-cloud/github-action-cli@v1
        with:
          service-account-key-json: ${{ secrets.YC_SA_KEY }}
          cloud-id:             ${{ secrets.YC_CLOUD_ID }}
          folder-id:            ${{ secrets.YC_FOLDER_ID }}

      - name: Docker login to YCR
        run: |
          yc container registry configure-docker

      - name: Build Docker image
        run: docker build -t $IMAGE_NAME .

      - name: Push Docker image to YCR
        run: docker push $IMAGE_NAME

      - name: Create .env file from GitHub Secret
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Copy files to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.VM_SSH_KEY }}
          source:   ".env,docker-compose.yml"
          target:   /home/${{ secrets.VM_USER }}/your-bot-folder/

      - name: SSH and restart bot
        uses: appleboy/ssh-action@v1.0.0
        with:
          host:     ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key:      ${{ secrets.VM_SSH_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/your-bot-folder/
            docker-compose pull
            docker-compose up -d --remove-orphans

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to:      ${{ secrets.TELEGRAM_TO }}
          token:   ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            В ${{ github.repository }}
            ${{ github.actor }} запушил коммит
            "${{ github.event.commits[0].message }}"
            Деплой stroyka-bot выполнен!
