name: Deploy to Yandex Cloud VM

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: cr.yandex/${{ secrets.YC_REGISTRY_ID }}/stroyka-bot:latest
  REMOTE_DIR: /home/${{ secrets.VM_USER }}/stroyka-bot

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install & configure Yandex Cloud CLI via apt
        run: |
          # 1) Добавляем репозиторий Yandex Cloud CLI
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc-deb/KEY.gpg \
            | sudo gpg --dearmor -o /usr/share/keyrings/yandexcloud-yc-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/yandexcloud-yc-archive-keyring.gpg] https://storage.yandexcloud.net/yandexcloud-yc-deb stable main" \
            | sudo tee /etc/apt/sources.list.d/yandex-cloud-cli.list

          # 2) Устанавливаем yc из репозитория
          sudo apt-get update
          sudo apt-get install -y yandex-cloud-cli

          # 3) Инжектим ключ в файл и настраиваем CLI
          echo "${{ secrets.YC_SA_KEY }}" > key.json
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}

          # 4) Проверим
          yc --version

      - name: Docker login to Yandex Container Registry
        run: |
          yc container registry configure-docker

      - name: Build & push Docker image
        run: |
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Create .env from secret
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.VM_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key

      - name: Copy files to VM
        run: |
          scp -o StrictHostKeyChecking=no -i deploy_key \
            .env docker-compose.yml \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:$REMOTE_DIR

      - name: SSH and restart bot
        run: |
          ssh -o StrictHostKeyChecking=no -i deploy_key \
            ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
              cd $REMOTE_DIR
              docker-compose pull
              docker-compose up -d --remove-orphans
            EOF

  send_message:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          to:    ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            В ${{ github.repository }}
            ${{ github.actor }} запушил коммит
            "${{ github.event.commits[0].message }}"
            Деплой stroyka_bot выполнен!
