name: Build & Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем код
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -t stroyka-bot:latest -f bot/Dockerfile .

      # 3) Упаковываем образ и через SSH грузим его на сервер
      - name: Send image to VM & reload container
        env:
          VM_HOST: ${{ secrets.VM_HOST }}
          VM_USER: ${{ secrets.VM_USER }}
        run: |
          # Подготавливаем приватный ключ
          echo "${{ secrets.VM_SSH_KEY }}" > deploy_key
          chmod 600 deploy_key

          # Сохраняем образ в поток, шлём по SSH и сразу делаем docker load & up
          docker save stroyka-bot:latest \
            | ssh -o StrictHostKeyChecking=no -i deploy_key \
                $VM_USER@$VM_HOST \
              "docker load && \
               cd stroyka-bot && \
               docker-compose up -d --build --remove-orphans"

      # 4) (опционально) отправляем уведомление в Telegram
      - name: Send Telegram notification
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to:      ${{ secrets.TELEGRAM_TO }}
          token:   ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            ✅ Деплой завершён!
            Репозиторий: ${{ github.repository }}
            Коммит: ${{ github.sha }}
